Fix broken build of core variant by adding missing include for VMThread
src/hotspot/share/runtime/java.cpp:533:7: error: use of undeclared identifier 'VMThread'
  if (VMThread::vm_thread() != NULL) {
      ^
src/hotspot/share/runtime/java.cpp:553:5: error: use of undeclared identifier 'VMThread'
    VMThread::execute(&op);
    ^
src/hotspot/share/runtime/java.cpp:553:24: error: declaration of reference variable 'op' requires an initializer
    VMThread::execute(&op);
                       ^~
3 errors generated.

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>